version: '3'
services:
  server:
    build: 'server'
    ports:
      - '80:8080'
    depends_on:
      - db
  db:
    build: 'postgres'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=grafeas
      - POSTGRES_USER=grafeas
  swagger:
    build: 'swagger'
    ports:
      - '8080:8080'
    environment:
      - SWAGGER_JSON=/grafeas.swagger.json
    depends_on:
      - server
